// AUTO-GENERATED — do not edit manually
// Priority 1: local .mp3  |  Priority 2: ElevenLabs API  |  Priority 3: Web Speech
// Generated with Voice ID: Xb7hH8MSUJpSbSDYk0k2 (Alice, ElevenLabs)
export const audioMap = {
  "A baker puts 5 buns in every box. She packs 4 boxes. How many buns did she pack — without counting one by one?": "/assets/audio/audio_a_baker_puts_5_buns_in_every_box_she_packs_4_boxes_how_many.mp3",
  "What if there's a faster way than counting one bun at a time?": "/assets/audio/audio_what_if_there_s_a_faster_way_than_counting_one_bun_at_a_time.mp3",
  "Aisha is setting up 5 tables for her birthday party. Each table seats 4 friends. She wants to know how many friends she can invite without counting one by one.": "/assets/audio/audio_aisha_is_setting_up_5_tables_for_her_birthday_party_each_tab.mp3",
  "We can see 5 separate tables. Each one has exactly 4 chairs — that's 5 equal groups of 4.": "/assets/audio/audio_we_can_see_5_separate_tables_each_one_has_exactly_4_chairs_t.mp3",
  "If we count in jumps of 4 — once for every table — we go 4, 8, 12, 16, 20. That's much faster than counting every chair!": "/assets/audio/audio_if_we_count_in_jumps_of_4_once_for_every_table_we_go_4_8_12.mp3",
  "5 tables, 4 chairs each, makes 20 chairs altogether. Aisha can invite 20 friends to her party!": "/assets/audio/audio_5_tables_4_chairs_each_makes_20_chairs_altogether_aisha_can.mp3",
  "Use the sliders to set the number of groups and items. Watch the total update live!": "/assets/audio/audio_use_the_sliders_to_set_the_number_of_groups_and_items_watch.mp3",
  "Drag the sliders to change the rows and columns of the dot array.": "/assets/audio/audio_drag_the_sliders_to_change_the_rows_and_columns_of_the_dot_a.mp3",
  "Choose a step size and tap Jump to skip-count along the number line.": "/assets/audio/audio_choose_a_step_size_and_tap_jump_to_skip_count_along_the_numb.mp3",
  "Tap the cells in the table to reveal the multiplication facts and spot the patterns!": "/assets/audio/audio_tap_the_cells_in_the_table_to_reveal_the_multiplication_fact.mp3",
  "Tell me one multiplication trick you learned today!": "/assets/audio/audio_tell_me_one_multiplication_trick_you_learned_today.mp3",
  "Amazing! That's the magic of multiplying!": "/assets/audio/audio_amazing_that_s_the_magic_of_multiplying.mp3",
  "Well done! You've got this!": "/assets/audio/audio_well_done_you_ve_got_this.mp3",
  "Brilliant! Skip-counting works every time!": "/assets/audio/audio_brilliant_skip_counting_works_every_time.mp3",
  "You got it! Keep going!": "/assets/audio/audio_you_got_it_keep_going.mp3",
  "Fantastic! That's one more fact in your brain!": "/assets/audio/audio_fantastic_that_s_one_more_fact_in_your_brain.mp3",
  "Let's try again — think about the equal groups!": "/assets/audio/audio_let_s_try_again_think_about_the_equal_groups.mp3",
  "Not quite — use skip-counting to check!": "/assets/audio/audio_not_quite_use_skip_counting_to_check.mp3",
  "So close! Try counting in jumps.": "/assets/audio/audio_so_close_try_counting_in_jumps.mp3",
  "Almost there — you can do it!": "/assets/audio/audio_almost_there_you_can_do_it.mp3",
  "4 baskets, each with 3 buns. How many buns in total?": "/assets/audio/audio_4_baskets_each_with_3_buns_how_many_buns_in_total.mp3",
  "Look at 4 baskets — each has 3 buns.": "/assets/audio/audio_look_at_4_baskets_each_has_3_buns.mp3",
  "Count in 3s: 3, 6, 9, 12.": "/assets/audio/audio_count_in_3s_3_6_9_12.mp3",
  "4 groups of 3 = 12. So 4 times 3 = 12.": "/assets/audio/audio_4_groups_of_3_12_so_4_times_3_12.mp3",
  "5 packs, each with 2 pencils. How many pencils altogether?": "/assets/audio/audio_5_packs_each_with_2_pencils_how_many_pencils_altogether.mp3",
  "There are 5 packs, each holding 2 pencils.": "/assets/audio/audio_there_are_5_packs_each_holding_2_pencils.mp3",
  "Count in 2s: 2, 4, 6, 8, 10.": "/assets/audio/audio_count_in_2s_2_4_6_8_10.mp3",
  "5 groups of 2 = 10. So 5 times 2 = 10.": "/assets/audio/audio_5_groups_of_2_10_so_5_times_2_10.mp3",
  "5 boxes, each holding 4 stickers. How many stickers in total?": "/assets/audio/audio_5_boxes_each_holding_4_stickers_how_many_stickers_in_total.mp3",
  "There are 5 boxes with 4 stickers each.": "/assets/audio/audio_there_are_5_boxes_with_4_stickers_each.mp3",
  "Count in 4s: 4, 8, 12, 16, 20.": "/assets/audio/audio_count_in_4s_4_8_12_16_20.mp3",
  "5 groups of 4 = 20. So 5 times 4 = 20.": "/assets/audio/audio_5_groups_of_4_20_so_5_times_4_20.mp3",
  "4 vases, each with 5 flowers. How many flowers are there?": "/assets/audio/audio_4_vases_each_with_5_flowers_how_many_flowers_are_there.mp3",
  "Count the vases — there are 4, each with 5 flowers.": "/assets/audio/audio_count_the_vases_there_are_4_each_with_5_flowers.mp3",
  "Count in 5s: 5, 10, 15, 20.": "/assets/audio/audio_count_in_5s_5_10_15_20.mp3",
  "4 groups of 5 = 20. So 4 times 5 = 20.": "/assets/audio/audio_4_groups_of_5_20_so_4_times_5_20.mp3",
  "4 rows of chairs, 7 chairs in each row. How many chairs?": "/assets/audio/audio_4_rows_of_chairs_7_chairs_in_each_row_how_many_chairs.mp3",
  "Think: 4 equal groups, 7 in each.": "/assets/audio/audio_think_4_equal_groups_7_in_each.mp3",
  "Count in 7s four times: 7, 14, 21, 28.": "/assets/audio/audio_count_in_7s_four_times_7_14_21_28.mp3",
  "4 groups of 7 = 28. So 4 times 7 = 28.": "/assets/audio/audio_4_groups_of_7_28_so_4_times_7_28.mp3",
  "5 fish tanks, each with 6 fish. How many fish in total?": "/assets/audio/audio_5_fish_tanks_each_with_6_fish_how_many_fish_in_total.mp3",
  "There are 5 tanks, each with 6 fish.": "/assets/audio/audio_there_are_5_tanks_each_with_6_fish.mp3",
  "Skip-count by 6 five times: 6, 12, 18, 24, 30.": "/assets/audio/audio_skip_count_by_6_five_times_6_12_18_24_30.mp3",
  "5 groups of 6 = 30. So 5 times 6 = 30.": "/assets/audio/audio_5_groups_of_6_30_so_5_times_6_30.mp3",
  "10 bags, each with 4 coins. How many coins altogether?": "/assets/audio/audio_10_bags_each_with_4_coins_how_many_coins_altogether.mp3",
  "There are 10 groups of 4 coins.": "/assets/audio/audio_there_are_10_groups_of_4_coins.mp3",
  "Multiply: 10 times 4 = 40.": "/assets/audio/audio_multiply_10_times_4_40.mp3",
  "10 groups of 4 = 40. So 10 times 4 = 40.": "/assets/audio/audio_10_groups_of_4_40_so_10_times_4_40.mp3",
  "4 shelves, each holding 8 books. How many books are there?": "/assets/audio/audio_4_shelves_each_holding_8_books_how_many_books_are_there.mp3",
  "You have 4 shelves — each holds 8 books.": "/assets/audio/audio_you_have_4_shelves_each_holds_8_books.mp3",
  "Count in 8s four times: 8, 16, 24, 32.": "/assets/audio/audio_count_in_8s_four_times_8_16_24_32.mp3",
  "4 groups of 8 = 32. So 4 times 8 = 32.": "/assets/audio/audio_4_groups_of_8_32_so_4_times_8_32.mp3",
  "5 jars, each with 9 marbles. How many marbles in total?": "/assets/audio/audio_5_jars_each_with_9_marbles_how_many_marbles_in_total.mp3",
  "There are 5 jars, each containing 9 marbles.": "/assets/audio/audio_there_are_5_jars_each_containing_9_marbles.mp3",
  "Skip-count by 9 five times: 9, 18, 27, 36, 45.": "/assets/audio/audio_skip_count_by_9_five_times_9_18_27_36_45.mp3",
  "5 groups of 9 = 45. So 5 times 9 = 45.": "/assets/audio/audio_5_groups_of_9_45_so_5_times_9_45.mp3",
  "4 crates, each with 9 oranges. How many oranges are there?": "/assets/audio/audio_4_crates_each_with_9_oranges_how_many_oranges_are_there.mp3",
  "You have 4 crates, each holding 9 oranges.": "/assets/audio/audio_you_have_4_crates_each_holding_9_oranges.mp3",
  "Count in 9s four times: 9, 18, 27, 36.": "/assets/audio/audio_count_in_9s_four_times_9_18_27_36.mp3",
  "4 groups of 9 = 36. So 4 times 9 = 36.": "/assets/audio/audio_4_groups_of_9_36_so_4_times_9_36.mp3",
  "A grid shows 2 rows of 4 dots. What is 2 times 4?": "/assets/audio/audio_a_grid_shows_2_rows_of_4_dots_what_is_2_times_4.mp3",
  "2 times 4 = 8. There are 8 dots in total.": "/assets/audio/audio_2_times_4_8_there_are_8_dots_in_total.mp3",
  "An array shows 3 rows and 5 columns. What is 3 times 5?": "/assets/audio/audio_an_array_shows_3_rows_and_5_columns_what_is_3_times_5.mp3",
  "3 times 5 = 15. There are 15 dots.": "/assets/audio/audio_3_times_5_15_there_are_15_dots.mp3",
  "A square array has 4 rows and 4 columns. How many dots?": "/assets/audio/audio_a_square_array_has_4_rows_and_4_columns_how_many_dots.mp3",
  "4 times 4 = 16.": "/assets/audio/audio_4_times_4_16.mp3",
  "A grid shows 5 rows of 5 stars each. What is 5 times 5?": "/assets/audio/audio_a_grid_shows_5_rows_of_5_stars_each_what_is_5_times_5.mp3",
  "5 times 5 = 25.": "/assets/audio/audio_5_times_5_25.mp3",
  "An array shows 4 rows and 6 columns of circles. What is 4 times 6?": "/assets/audio/audio_an_array_shows_4_rows_and_6_columns_of_circles_what_is_4_tim.mp3",
  "4 times 6 = 24.": "/assets/audio/audio_4_times_6_24.mp3",
  "A grid has 10 rows and 3 columns. What is 10 times 3?": "/assets/audio/audio_a_grid_has_10_rows_and_3_columns_what_is_10_times_3.mp3",
  "10 times 3 = 30.": "/assets/audio/audio_10_times_3_30.mp3",
  "An array shows 5 rows and 7 columns. What is 5 times 7?": "/assets/audio/audio_an_array_shows_5_rows_and_7_columns_what_is_5_times_7.mp3",
  "5 times 7 = 35.": "/assets/audio/audio_5_times_7_35.mp3",
  "A grid has 4 rows and 10 columns of dots. What is 4 times 10?": "/assets/audio/audio_a_grid_has_4_rows_and_10_columns_of_dots_what_is_4_times_10.mp3",
  "4 times 10 = 40.": "/assets/audio/audio_4_times_10_40.mp3",
  "An array shows 4 rows and 9 columns. What is 4 times 9?": "/assets/audio/audio_an_array_shows_4_rows_and_9_columns_what_is_4_times_9.mp3",
  "4 times 9 = 36.": "/assets/audio/audio_4_times_9_36.mp3",
  "An array has 5 rows and 10 columns. What is 5 times 10?": "/assets/audio/audio_an_array_has_5_rows_and_10_columns_what_is_5_times_10.mp3",
  "5 times 10 = 50.": "/assets/audio/audio_5_times_10_50.mp3",
  "4 times 2 equals what?": "/assets/audio/audio_4_times_2_equals_what.mp3",
  "4 times 2 = 8.": "/assets/audio/audio_4_times_2_8.mp3",
  "5 times 3 equals what?": "/assets/audio/audio_5_times_3_equals_what.mp3",
  "5 times 3 = 15.": "/assets/audio/audio_5_times_3_15.mp3",
  "4 times blank equals 24. What is the missing number?": "/assets/audio/audio_4_times_blank_equals_24_what_is_the_missing_number.mp3",
  "4 times 6 = 24. The missing number is 6.": "/assets/audio/audio_4_times_6_24_the_missing_number_is_6.mp3",
  "5 times blank equals 40. What is the missing number?": "/assets/audio/audio_5_times_blank_equals_40_what_is_the_missing_number.mp3",
  "5 times 8 = 40. The missing number is 8.": "/assets/audio/audio_5_times_8_40_the_missing_number_is_8.mp3",
  "10 times 6 equals what?": "/assets/audio/audio_10_times_6_equals_what.mp3",
  "10 times 6 = 60.": "/assets/audio/audio_10_times_6_60.mp3",
  "10 times blank equals 70. What is the missing number?": "/assets/audio/audio_10_times_blank_equals_70_what_is_the_missing_number.mp3",
  "10 times 7 = 70. The missing number is 7.": "/assets/audio/audio_10_times_7_70_the_missing_number_is_7.mp3",
  "Blank times 8 equals 32. What is the missing number?": "/assets/audio/audio_blank_times_8_equals_32_what_is_the_missing_number.mp3",
  "4 times 8 = 32. The missing number is 4.": "/assets/audio/audio_4_times_8_32_the_missing_number_is_4.mp3",
  "5 times blank equals 45. What is the missing number?": "/assets/audio/audio_5_times_blank_equals_45_what_is_the_missing_number.mp3",
  "5 times 9 = 45. The missing number is 9.": "/assets/audio/audio_5_times_9_45_the_missing_number_is_9.mp3",
  "4 times 10 equals what?": "/assets/audio/audio_4_times_10_equals_what.mp3",
  "Blank times 10 equals 50. What is the missing number?": "/assets/audio/audio_blank_times_10_equals_50_what_is_the_missing_number.mp3",
  "5 times 10 = 50. The missing number is 5.": "/assets/audio/audio_5_times_10_50_the_missing_number_is_5.mp3",
  "Aisha sets up 5 tables. Each table has 4 chairs. How many chairs in total?": "/assets/audio/audio_aisha_sets_up_5_tables_each_table_has_4_chairs_how_many_chai.mp3",
  "5 times 4 = 20. Aisha needs 20 chairs.": "/assets/audio/audio_5_times_4_20_aisha_needs_20_chairs.mp3",
  "Mei buys 4 packs of stickers. Each pack has 5 stickers. How many stickers does Mei have?": "/assets/audio/audio_mei_buys_4_packs_of_stickers_each_pack_has_5_stickers_how_ma.mp3",
  "4 times 5 = 20. Mei has 20 stickers.": "/assets/audio/audio_4_times_5_20_mei_has_20_stickers.mp3",
  "Wei Ming packs 5 boxes of buns. Each box holds 6 buns. How many buns are packed?": "/assets/audio/audio_wei_ming_packs_5_boxes_of_buns_each_box_holds_6_buns_how_man.mp3",
  "5 times 6 = 30. Wei Ming packed 30 buns.": "/assets/audio/audio_5_times_6_30_wei_ming_packed_30_buns.mp3",
  "Priya counts 10 flowers in each vase. She has 5 vases. How many flowers in total?": "/assets/audio/audio_priya_counts_10_flowers_in_each_vase_she_has_5_vases_how_man.mp3",
  "10 times 5 = 50. There are 50 flowers.": "/assets/audio/audio_10_times_5_50_there_are_50_flowers.mp3",
  "Ahmad buys 4 bags of marbles. Each bag holds 7 marbles. How many marbles does Ahmad have?": "/assets/audio/audio_ahmad_buys_4_bags_of_marbles_each_bag_holds_7_marbles_how_ma.mp3",
  "4 times 7 = 28. Ahmad has 28 marbles.": "/assets/audio/audio_4_times_7_28_ahmad_has_28_marbles.mp3",
  "Ryan saves 10 cents every day for 8 days. How many cents does he save in total?": "/assets/audio/audio_ryan_saves_10_cents_every_day_for_8_days_how_many_cents_does.mp3",
  "10 times 8 = 80. Ryan saves 80 cents.": "/assets/audio/audio_10_times_8_80_ryan_saves_80_cents.mp3",
  "Siti places 4 rows of coins on a table. Each row has 8 coins. How many coins are there?": "/assets/audio/audio_siti_places_4_rows_of_coins_on_a_table_each_row_has_8_coins.mp3",
  "4 times 8 = 32. There are 32 coins.": "/assets/audio/audio_4_times_8_32_there_are_32_coins.mp3",
  "Jun has 5 fish tanks. Each tank holds 9 fish. How many fish does Jun have?": "/assets/audio/audio_jun_has_5_fish_tanks_each_tank_holds_9_fish_how_many_fish_do.mp3",
  "5 times 9 = 45. Jun has 45 fish.": "/assets/audio/audio_5_times_9_45_jun_has_45_fish.mp3",
  "Kavya arranges 4 trays. Each tray has 10 cupcakes. How many cupcakes are there?": "/assets/audio/audio_kavya_arranges_4_trays_each_tray_has_10_cupcakes_how_many_cu.mp3",
  "4 times 10 = 40. There are 40 cupcakes.": "/assets/audio/audio_4_times_10_40_there_are_40_cupcakes.mp3",
  "Xiao Ling counts 5 minutes for each problem. There are 10 problems. How many minutes in total?": "/assets/audio/audio_xiao_ling_counts_5_minutes_for_each_problem_there_are_10_pro.mp3",
  "5 times 10 = 50. It takes 50 minutes.": "/assets/audio/audio_5_times_10_50_it_takes_50_minutes.mp3",
  "4, 8, blank, 16, 20. What is the missing number?": "/assets/audio/audio_4_8_blank_16_20_what_is_the_missing_number.mp3",
  "Counting in 4s: 4, 8, 12, 16, 20. The missing number is 12.": "/assets/audio/audio_counting_in_4s_4_8_12_16_20_the_missing_number_is_12.mp3",
  "5, 10, 15, blank, 25. What is the missing number?": "/assets/audio/audio_5_10_15_blank_25_what_is_the_missing_number.mp3",
  "Counting in 5s: 5, 10, 15, 20, 25. The missing number is 20.": "/assets/audio/audio_counting_in_5s_5_10_15_20_25_the_missing_number_is_20.mp3",
  "10, 20, blank, 40, 50. What is the missing number?": "/assets/audio/audio_10_20_blank_40_50_what_is_the_missing_number.mp3",
  "Counting in 10s: 10, 20, 30, 40, 50. The missing number is 30.": "/assets/audio/audio_counting_in_10s_10_20_30_40_50_the_missing_number_is_30.mp3",
  "4, blank, 12, 16, 20. What is the missing number?": "/assets/audio/audio_4_blank_12_16_20_what_is_the_missing_number.mp3",
  "Counting in 4s: 4, 8, 12, 16, 20. The missing number is 8.": "/assets/audio/audio_counting_in_4s_4_8_12_16_20_the_missing_number_is_8.mp3",
  "20, 25, 30, 35, blank. What is the missing number?": "/assets/audio/audio_20_25_30_35_blank_what_is_the_missing_number.mp3",
  "Counting in 5s: the missing number is 40.": "/assets/audio/audio_counting_in_5s_the_missing_number_is_40.mp3",
  "40, blank, 60, 70, 80. What is the missing number?": "/assets/audio/audio_40_blank_60_70_80_what_is_the_missing_number.mp3",
  "Counting in 10s: 40, 50, 60. The missing number is 50.": "/assets/audio/audio_counting_in_10s_40_50_60_the_missing_number_is_50.mp3",
  "28, 32, blank, 40, 44. What is the missing number?": "/assets/audio/audio_28_32_blank_40_44_what_is_the_missing_number.mp3",
  "Counting in 4s: 28, 32, 36, 40, 44. The missing number is 36.": "/assets/audio/audio_counting_in_4s_28_32_36_40_44_the_missing_number_is_36.mp3",
  "45, blank, 55, 60, 65. What is the missing number?": "/assets/audio/audio_45_blank_55_60_65_what_is_the_missing_number.mp3",
  "Counting in 5s: the missing number is 50.": "/assets/audio/audio_counting_in_5s_the_missing_number_is_50.mp3",
  "32, 36, blank, 44, 48. What is the missing number?": "/assets/audio/audio_32_36_blank_44_48_what_is_the_missing_number.mp3",
  "Counting in 4s: the missing number is 40.": "/assets/audio/audio_counting_in_4s_the_missing_number_is_40.mp3",
  "60, 70, 80, blank, 100. What is the missing number?": "/assets/audio/audio_60_70_80_blank_100_what_is_the_missing_number.mp3",
  "Counting in 10s: 60, 70, 80, 90, 100. The missing number is 90.": "/assets/audio/audio_counting_in_10s_60_70_80_90_100_the_missing_number_is_90.mp3",
  "Is 4 times 3 equal to 12? True or False?": "/assets/audio/audio_is_4_times_3_equal_to_12_true_or_false.mp3",
  "4 times 3 = 12. This is TRUE.": "/assets/audio/audio_4_times_3_12_this_is_true.mp3",
  "Is 5 times 6 equal to 35? True or False?": "/assets/audio/audio_is_5_times_6_equal_to_35_true_or_false.mp3",
  "5 times 6 = 30, not 35. This is FALSE.": "/assets/audio/audio_5_times_6_30_not_35_this_is_false.mp3",
  "Is 10 times 4 equal to 40? True or False?": "/assets/audio/audio_is_10_times_4_equal_to_40_true_or_false.mp3",
  "10 times 4 = 40. This is TRUE.": "/assets/audio/audio_10_times_4_40_this_is_true.mp3",
  "Is 4 times 5 equal to 25? True or False?": "/assets/audio/audio_is_4_times_5_equal_to_25_true_or_false.mp3",
  "4 times 5 = 20, not 25. This is FALSE.": "/assets/audio/audio_4_times_5_20_not_25_this_is_false.mp3",
  "Is 5 times 8 equal to 40? True or False?": "/assets/audio/audio_is_5_times_8_equal_to_40_true_or_false.mp3",
  "5 times 8 = 40. This is TRUE.": "/assets/audio/audio_5_times_8_40_this_is_true.mp3",
  "Is 4 times 7 equal to 26? True or False?": "/assets/audio/audio_is_4_times_7_equal_to_26_true_or_false.mp3",
  "4 times 7 = 28, not 26. This is FALSE.": "/assets/audio/audio_4_times_7_28_not_26_this_is_false.mp3",
  "Is 10 times 9 equal to 90? True or False?": "/assets/audio/audio_is_10_times_9_equal_to_90_true_or_false.mp3",
  "10 times 9 = 90. This is TRUE.": "/assets/audio/audio_10_times_9_90_this_is_true.mp3",
  "Is 4 times 9 equal to 38? True or False?": "/assets/audio/audio_is_4_times_9_equal_to_38_true_or_false.mp3",
  "4 times 9 = 36, not 38. This is FALSE.": "/assets/audio/audio_4_times_9_36_not_38_this_is_false.mp3",
  "Is 5 times 10 equal to 50? True or False?": "/assets/audio/audio_is_5_times_10_equal_to_50_true_or_false.mp3",
  "5 times 10 = 50. This is TRUE.": "/assets/audio/audio_5_times_10_50_this_is_true.mp3",
  "Is 4 times 10 equal to 14? True or False?": "/assets/audio/audio_is_4_times_10_equal_to_14_true_or_false.mp3",
  "4 times 10 = 40, not 14. This is FALSE.": "/assets/audio/audio_4_times_10_40_not_14_this_is_false.mp3",
  "Blank times 5 equals 20. What is the missing number?": "/assets/audio/audio_blank_times_5_equals_20_what_is_the_missing_number.mp3",
  "4 times 5 = 20. The missing number is 4.": "/assets/audio/audio_4_times_5_20_the_missing_number_is_4.mp3",
  "4 times blank equals 16. What is the missing number?": "/assets/audio/audio_4_times_blank_equals_16_what_is_the_missing_number.mp3",
  "4 times 4 = 16. The missing number is 4.": "/assets/audio/audio_4_times_4_16_the_missing_number_is_4.mp3",
  "Blank times 10 equals 30. What is the missing number?": "/assets/audio/audio_blank_times_10_equals_30_what_is_the_missing_number.mp3",
  "3 times 10 = 30. The missing number is 3.": "/assets/audio/audio_3_times_10_30_the_missing_number_is_3.mp3",
  "5 times blank equals 35. What is the missing number?": "/assets/audio/audio_5_times_blank_equals_35_what_is_the_missing_number.mp3",
  "5 times 7 = 35. The missing number is 7.": "/assets/audio/audio_5_times_7_35_the_missing_number_is_7.mp3",
  "Blank times 4 equals 24. What is the missing number?": "/assets/audio/audio_blank_times_4_equals_24_what_is_the_missing_number.mp3",
  "6 times 4 = 24. The missing number is 6.": "/assets/audio/audio_6_times_4_24_the_missing_number_is_6.mp3",
  "Blank times 5 equals 45. What is the missing number?": "/assets/audio/audio_blank_times_5_equals_45_what_is_the_missing_number.mp3",
  "9 times 5 = 45. The missing number is 9.": "/assets/audio/audio_9_times_5_45_the_missing_number_is_9.mp3",
  "4 times blank equals 36. What is the missing number?": "/assets/audio/audio_4_times_blank_equals_36_what_is_the_missing_number.mp3",
  "4 times 9 = 36. The missing number is 9.": "/assets/audio/audio_4_times_9_36_the_missing_number_is_9.mp3",
  "Blank times 10 equals 70. What is the missing number?": "/assets/audio/audio_blank_times_10_equals_70_what_is_the_missing_number.mp3",
  "7 times 10 = 70. The missing number is 7.": "/assets/audio/audio_7_times_10_70_the_missing_number_is_7.mp3",
  "5 times blank equals 50. What is the missing number?": "/assets/audio/audio_5_times_blank_equals_50_what_is_the_missing_number.mp3",
  "5 times 10 = 50. The missing number is 10.": "/assets/audio/audio_5_times_10_50_the_missing_number_is_10.mp3",
  "Blank times 4 equals 40. What is the missing number?": "/assets/audio/audio_blank_times_4_equals_40_what_is_the_missing_number.mp3",
  "10 times 4 = 40. The missing number is 10.": "/assets/audio/audio_10_times_4_40_the_missing_number_is_10.mp3",
  "What is 4 times 1?": "/assets/audio/audio_what_is_4_times_1.mp3",
  "4 times 1 = 4.": "/assets/audio/audio_4_times_1_4.mp3",
  "What is 5 times 1?": "/assets/audio/audio_what_is_5_times_1.mp3",
  "5 times 1 = 5.": "/assets/audio/audio_5_times_1_5.mp3",
  "What is 4 times 4?": "/assets/audio/audio_what_is_4_times_4.mp3",
  "What is 5 times 5?": "/assets/audio/audio_what_is_5_times_5.mp3",
  "What is 10 times 5?": "/assets/audio/audio_what_is_10_times_5.mp3",
  "10 times 5 = 50.": "/assets/audio/audio_10_times_5_50.mp3",
  "What is 4 times 6?": "/assets/audio/audio_what_is_4_times_6.mp3",
  "What is 5 times 7?": "/assets/audio/audio_what_is_5_times_7.mp3",
  "What is 4 times 8?": "/assets/audio/audio_what_is_4_times_8.mp3",
  "4 times 8 = 32.": "/assets/audio/audio_4_times_8_32.mp3",
  "What is 10 times 9?": "/assets/audio/audio_what_is_10_times_9.mp3",
  "10 times 9 = 90.": "/assets/audio/audio_10_times_9_90.mp3",
  "What is 4 times 10?": "/assets/audio/audio_what_is_4_times_10.mp3",
  "Which of these is a multiple of 5?": "/assets/audio/audio_which_of_these_is_a_multiple_of_5.mp3",
  "25 is a multiple of 5. Multiples of 5 end in 0 or 5.": "/assets/audio/audio_25_is_a_multiple_of_5_multiples_of_5_end_in_0_or_5.mp3",
  "Which of these is a multiple of 10?": "/assets/audio/audio_which_of_these_is_a_multiple_of_10.mp3",
  "30 is a multiple of 10. Multiples of 10 always end in 0.": "/assets/audio/audio_30_is_a_multiple_of_10_multiples_of_10_always_end_in_0.mp3",
  "Which of these is NOT a multiple of 5?": "/assets/audio/audio_which_of_these_is_not_a_multiple_of_5.mp3",
  "18 does not end in 0 or 5, so it is not a multiple of 5.": "/assets/audio/audio_18_does_not_end_in_0_or_5_so_it_is_not_a_multiple_of_5.mp3",
  "Which of these is a multiple of 4?": "/assets/audio/audio_which_of_these_is_a_multiple_of_4.mp3",
  "28 is a multiple of 4. 4 times 7 = 28.": "/assets/audio/audio_28_is_a_multiple_of_4_4_times_7_28.mp3",
  "Which of these is NOT a multiple of 10?": "/assets/audio/audio_which_of_these_is_not_a_multiple_of_10.mp3",
  "45 ends in 5, so it is not a multiple of 10.": "/assets/audio/audio_45_ends_in_5_so_it_is_not_a_multiple_of_10.mp3",
  "Which is the largest multiple of 4 that is less than 30?": "/assets/audio/audio_which_is_the_largest_multiple_of_4_that_is_less_than_30.mp3",
  "28 is 4 times 7 = 28, the largest multiple of 4 below 30.": "/assets/audio/audio_28_is_4_times_7_28_the_largest_multiple_of_4_below_30.mp3",
  "Which of these is a multiple of both 4 and 5?": "/assets/audio/audio_which_of_these_is_a_multiple_of_both_4_and_5.mp3",
  "20 equals 4 times 5 and 5 times 4. It appears in both tables.": "/assets/audio/audio_20_equals_4_times_5_and_5_times_4_it_appears_in_both_tables.mp3",
  "How many times do products in the times 4 table go up by?": "/assets/audio/audio_how_many_times_do_products_in_the_times_4_table_go_up_by.mp3",
  "Each product in the times 4 table is 4 more than the previous.": "/assets/audio/audio_each_product_in_the_times_4_table_is_4_more_than_the_previou.mp3",
  "What is the last digit of every multiple of 10?": "/assets/audio/audio_what_is_the_last_digit_of_every_multiple_of_10.mp3",
  "Every multiple of 10 ends in 0.": "/assets/audio/audio_every_multiple_of_10_ends_in_0.mp3",
  "How many multiples of 4 are there from 1 to 40?": "/assets/audio/audio_how_many_multiples_of_4_are_there_from_1_to_40.mp3",
  "There are 10 multiples of 4 from 1 to 40.": "/assets/audio/audio_there_are_10_multiples_of_4_from_1_to_40.mp3"
};
